### ISSUE TITLE
Quarkus 3.6.0 Fails to Start

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-embedded-postgresql#69]
Quarkus 3.2.9 has this warning:

```shell
[WARNING] /C:/temp/quarkus/quarkus-embedded-postgresql-main/deployment/src/main/java/io/quarkiverse/embedded/postgresql/deployment/EmbeddedPostgreSQLProcessor.java:
[41,27] io.quarkus.deployment.builditem.RunTimeConfigurationSourceValueBuildItem in io.quarkus.deployment.builditem has been deprecated
```

In 3.6.0 my server fails to start with..

```shell
2023-12-04 15:59:50,726 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-2) Failed to start quarkus: java.lang.NoClassDefFoundError: io/quarkus/deployment/builditem/RunTimeConfigurationSourceValueBuildItem
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:160)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:264)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:60)
```

**Comment by melloware** [comment]
cc @radcortez

**Comment by melloware** [comment]
OK let me try and study what you did there.

**Comment by melloware** [comment]
@radcortez any chance you could help with this.  I am totally stuck on how to make this work like it does in 3.2.9. Because of the runtime Recorder stuff.

**Comment by melloware** [comment]
Its the `Recorder` and that fact that the runtime values are only available here:

```java
    public RuntimeValue<ConfigSourceProvider> configSources(RuntimeValue<StartupInfo> info) {
        return new RuntimeValue<>(new EmbeddedPostgreSQLConfigSourceProvider(info.getValue()));
    }
```

So I can't figure out how to "get rid of this recorder" to make it work with the new 3.6.0 way of using `RunTimeConfigBuilderBuildItem `

**Comment by fjtirado** [comment]
Yes, once RunTimeConfigBuilderBuildItem was removed, the recorder is a goner. We were planning to work on this, but if you have already started, @melloware, please file the PR.

**Comment by melloware** [comment]
I did not start on this but I had the same idea as you @fjtirado switch to Build Time config.  If you want to work on it be my guest if not I can work on something?

**Comment by fjtirado** [comment]
@melloware good ;). 
Ill try to file a PR by the end of this week. Then, once it is merged, you update this other PR https://github.com/quarkiverse/quarkus-embedded-postgresql/pull/72 and we are settle ;)

**Comment by fjtirado** [comment]
@melloware I was unable to dedicate time to this during this week (end of year), if you can work these days on that, please go ahead and I will review when I return. 
Sorry about that

**Comment by melloware** [comment]
@fjtirado this is definitely messier than I thought. When I remove the recorder and make it runtime utils it now fails because shutdown can only be done from a Recorder.

```java
shutdownContext.addShutdownTask(() -> {
            try {
                pg.close();
            } catch (IOException e) {
                logger.warn("Error shutting down embedded postgres", e);
            }
        });
```

I think we might have to switch this to use DevService which has an auto close mechanism?

**Comment by melloware** [comment]
OK I submitted a PR as a work in progress. I have most everything working but the runtime config stuff.

**Comment by melloware** [comment]
OK all updates have been made and its working as expected now in Quarkus 3.7.1
